import type { Metadata } from "next";
import "../styles/globals.css";
import Providers from "@/app/providers";
import Nav from "@/components/Nav";
import { Pretendard } from "@/styles/fonts/font";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={Pretendard.className}>
      <body className="mx-auto min-w-[320px] max-w-screen-md">
        <Providers>
          <main className="flex flex-col">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
